name: Pre-Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  CACHE_NAME: cache-node-modules
jobs:
  release:
    name: Build, Test & Publish
    runs-on: ubuntu-18.04
    if: |
      !contains(github.event.head_commit.message, 'chore:')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.10.0
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install GraphViz
        run: sudo apt update && sudo apt install graphviz
      - name: Install dependencies
        run: yarn
      - name: Compile Typescript
        run: yarn build
      - name: Run Tests
        run: yarn test
      - name: Generate Dependency Graphs
        run: yarn graph:all
      - name: Release
        run: npx semantic-release
